/*
 * version.h - build identification for BeaverMQ.
 *
 * beaver_build_stamp is generated by the Makefile at LINK time (see the
 * version_src rule), so it identifies the exact build of the binary. It is
 * printed by `beavermq --version`, logged at startup, and exposed via the
 * unauthenticated GET /api/healthz - which lets a deploy script verify that
 * the RUNNING process matches the binary it just copied (a broker that was
 * not restarted after a deploy keeps executing the old code).
 */
#ifndef BEAVERMQ_VERSION_H
#define BEAVERMQ_VERSION_H

#define BEAVER_VERSION "1.0.0"

extern const char beaver_build_stamp[];

#endif /* BEAVERMQ_VERSION_H */
